### ISSUE TITLE
Include end date in calculation

### ISSUE THREAD

**Issue by rafael-guerra-www** [felipenoris/BusinessDays.jl#55]
Hello @felipenoris, would you mind explaining the rationale when counting the business days between two dates, to not include the end date?

In example below, the start date is a US public holiday and the end date is a working business day and the result for counting business days is zero. Same result if the start date is equal to the end date.

```julia
using BusinessDays, Dates
cal = BusinessDays.USSettlement()   # US calendar
d1 = Date(2021, 11, 25)
d2 = Date(2021, 11, 26)
bdayscount(cal, d1, d2)    # count = 0
bdayscount(cal, d2, d2)    # count = 0
```

Could you also confirm that the workaround to include the end date would be to add one day to d2:  `bdayscount(cal, d1, d2 + Day(1))`?

It might be worth adding a note on this in the documentation.

Thanks and regards.

**Comment by felipenoris** [comment]
The convention to not include the end date is due to the fact that, in Financial Engineering, if you invest money at date `d1` and redeem it at date `d2`, the interest depends on the **number of working days that the money slept in you money account**.

If you need to include the end date, maybe of can start with the result of `bdayscount` and adjust from that. I suggest to test your code on edge cases.
